services:
  app:
    image: 'docker-spring-boot-postgres:latest'
    build:
      context: ../
      dockerfile: docker/Dockerfile
    container_name: app
    depends_on:
      - db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1564
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgresdocker
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=1564
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "8080:8080"

  db:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1564
      - POSTGRES_DB=postgresdocker
    volumes:
    - ../src/Effortly-Time-Tracker/src/main/resources/sql/CreateTables.sql:/docker-entrypoint-initdb.d/CreateTables.sql

  swagger-ui:
    image: nginx:1.27
    container_name: swagger-ui
    volumes:
      - ./swagger:/usr/share/nginx/html
    ports:
      - "8081:80"
#  nginx:
#    image: nginx:latest
#    container_name: nginx
#    volumes:
#      - ./nginx.conf:/etc/nginx/nginx.conf
#    ports:
#      - "8081:80"
#    depends_on:
#      - app
    # Service to validate and bundle OpenAPI JSON
