services:
  app:
    image: 'docker-spring-boot-postgres:latest'
    build:
      context: ../
      dockerfile: docker/Dockerfile
    container_name: app
    depends_on:
      - db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1564
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgresdocker
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=1564
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "8080:8080"
    networks:
      - app-network

  db:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1564
      - POSTGRES_DB=postgresdocker
    volumes:
    - ../src/Effortly-Time-Tracker/src/main/resources/sql/CreateTables.sql:/docker-entrypoint-initdb.d/CreateTables.sql
    networks:
      - app-network

  swagger-ui:
    image: nginx:1.27
    container_name: swagger-ui
    volumes:
      - ./swagger:/usr/share/nginx/html/swagger-ui
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./static:/usr/share/nginx/html/static
    ports:
      - "8081:80"
    networks:
      - app-network
    depends_on:
      - app
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com  # Замените на ваш email
      - PGADMIN_DEFAULT_PASSWORD=1564         # Замените на ваш пароль
    ports:
      - "5050:80"
    networks:
      - app-network
    depends_on:
      - db


networks:
  app-network:
    driver: bridge
