name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    env:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://localhost:5432/postgresdocker"
      SPRING_DATASOURCE_USERNAME: "postgres"
      SPRING_DATASOURCE_PASSWORD: "1564"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build and Test with Maven
        run: mvn -f src/Effortly-Time-Tracker/pom.xml clean verify

      - name: Build Docker Image
        run: docker build -t volnamax1/effortly-time-tracker -f docker/Dockerfile .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Push Docker Image
        run: |
          docker tag volnamax1/effortly-time-tracker volnamax1/effortly-time-tracker:latest
          docker push volnamax1/effortly-time-tracker:latest
