name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 1564
          POSTGRES_DB: postgresdocker
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Wait for Database
        run: |
          for i in {1..10}; do
            nc -z localhost 5432 && echo "Database is ready" && exit 0
            echo "Waiting for database..."
            sleep 5
          done
          echo "Database not ready" && exit 1

      - name: Build and Test with Maven
        env:
          SPRING_DATASOURCE_URL: "jdbc:postgresql://localhost:5432/postgresdocker"
          SPRING_DATASOURCE_USERNAME: "postgres"
          SPRING_DATASOURCE_PASSWORD: "1564"
        run: mvn -f src/Effortly-Time-Tracker/pom.xml clean verify
